#!/usr/bin/env bash
#Bash script that configures the container to fit the above requirements
pkill apache2
chown nginx:nginx /etc/nginx/nginx.conf
chmod 700/etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/site-enabled/default
sudo -u nginx service nginx start
